### ISSUE TITLE
[Swagger] SpringBoot 2.6.x 이상에서 Swagger3.0 연동시 생기는 이슈

### ISSUE THREAD

**Issue by DolphaGo** [DolphaGo/DolphaGo#102]
```
Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
```

> **이슈 원인**

spring boot 2.6.0부터 요청 경로를 ControllerHandler에 매칭시키기 위한 전략의 기본값이 `ant_path_matcher` 전략 -> `path_pattern_parser` 전략으로 변경되었기 때문이다.

- `application.properties`에서 `spring.mvc.pathmatch.matching-strategy=ant_path_matcher`로 default 값을 변경한다.
```yml
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
```
