### ISSUE TITLE
h2 console testdb 접속이 안될 때 

### ISSUE THREAD

**Issue by DolphaGo** [DolphaGo/DolphaGo#87]
Database "mem:testdb" not found, either pre-create it or allow remote database creation (not recommended in secure environments)

대략 위와 같은 에러로 나타난다.
이는 datasource에 대한 정보가 없어서 그런 것. appilcation.yml(or properties)에 datasource 정보를 입력해주면 해결된다.

```
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
```
